name: Casa de alguien

adapter:
  kind: dry-run
  # but really
  # kind: hue
  # username: some-hue-bridge-key
  # ip: 192.168.0.256 # the hue bridge's ip
  # device: 53 # the device number
  # see `puerta hue setup`

http:
  listen: "localhost:8080"
  origin: http://localhost:8080
