name: Casa de alguien

adapter:
  kind: dry-run
  # but really
  # kind: hue
  # username: some-hue-bridge-key
  # ip: 192.168.0.256 # the hue bridge's ip
  # device: 53 # the device number
  # see `puerta hue setup`

http:
  listen: "localhost:8080"
  origin: http://localhost:8080
  protocol: http

push:
  key:
    # https://github.com/SherClockHolmes/webpush-go#generating-vapid-keys
    # wish it was simpler to export base64-url-encoded raw bytes from openssl, but alas
    private:
    public:
